# Generated by Django 3.1 on 2020-08-19 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0002_auto_20200817_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('community', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date(2020, 8, 19))),
            ],
            options={
                'verbose_name': 'Нотификация',
                'verbose_name_plural': 'Нотификации',
            },
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 19)),
        ),
    ]
