# Generated by Django 3.1 on 2020-08-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0004_auto_20200820_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationread',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='notificationread',
            old_name='user',
            new_name='users',
        ),
    ]
